name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      - run: mkdir -p ~/.config/yandex-cloud
      - run: mkdir -p ~/.local/bin
      - run: echo $PATH
      - run: ln -s ~/yandex-cloud/bin/yc /home/linuxbrew/.linuxbrew/bin/yc
      - run: pip install poetry
      - run: yc config set token "${{ secrets.YC_TOKEN }}"
      - run: yc config set folder-id "${{ secrets.YC_FOLDER }}"
      - run: ./deploy.sh
        env:
          SERVICE_ACC: ${{ secrets.SERVICE_ACC }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FOLDER: ${{ secrets.YC_FOLDER }}
          TG_USERS_WHITELIST: ${{ secrets.TG_USERS_WHITELIST }}
